### ISSUE TITLE
Can't draw circuits with more than 9 qubits.

### ISSUE THREAD

**Issue by cnktysz** [projekter/yquant#5]
**Describe the bug**
When there are at least 10 qubits defined, the compiler gives illegal unit of measure (pt inserted) error.

**To Reproduce**
\begin{tikzpicture}
\begin{yquant}
qubit { } a[10];
measure a;
\end{yquant}
\end{tikzpicture}

**Environment**
I am using MacTeX Shop Version 4.44. using LaTeX to compile the code.

**Comment by projekter** [comment]
Confirmed, please try with the current master branch. This should fix the problem. If you agree, I'll push an update to CTAN.
https://github.com/projekter/yquant/commit/53e834a3cfb7e288b071612c7280650797f46ee3#diff-fc4d1da5736a128759a73421aef51d5d

**Comment by cnktysz** [comment]
It now works with the update. Thanks.
