### ISSUE TITLE
shorten doesn't work for 2-qubit barriers

### ISSUE THREAD

**Issue by ajavadia** [projekter/yquant#6]
**Describe the bug**
`shorten` works for `yquant-line` when it's on 1 wire, but not 2 wires.

**To Reproduce**
In the example from docs, page 72, change `a` to a two-qubit register. It will no longer change the size of the barrier.

The code would be:
```tex
% \usetikzlibrary{quotes}
\begin{tikzpicture}[label distance=4mm]
   \begin{yquant}[operators/every barrier/.append style={red, thick, shorten <= -2.5mm, shorten >= -2.5mm}]
      qubit {$\ket0$} a[2];
      h a;
      ["1"]
      barrier (a);
      phase {[label distance=0pt]$\varphi$} a;
      ["2"]
      barrier (a);
      h a;
      ["3"]
      barrier (a);
      output {$\cos\frac\varphi2 \ket0 - i\sin\frac\varphi2 \ket1$};
   \end{yquant}
\end{tikzpicture}
```

**Expected output**
Should stretch the barrier from bottom and top.

**Screenshots**
![image](https://user-images.githubusercontent.com/8622381/97250300-08094000-17dc-11eb-8aac-20b1a6b03638.png)

**Environment**
 - TeX distribution: Texlive 2020
 - Compiler (pdf, Lua, ...): pdflatex

**Comment by projekter** [comment]
Please check against the current master. It was more of a coincidence that shortening "worked" at all on single qubits - I accidentally implemented an enlargement with the shortening key. Now the direction is the correct one, I hope this does not break existing layouts.
